### ISSUE TITLE
[PROBLEM]: qt.qpa.xcb: could not connect to display

### ISSUE THREAD

**Issue by jvondermarck** [fffaraz/docker-qt#13]
Hi,

I try to run a Widget QT app and I have this error message : 

```
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.
```

Here a screenshot of my toolchain to execute my app : 
![image](https://user-images.githubusercontent.com/62793491/212160254-d515ad04-a05d-4cf8-93fd-f5f3fda52c97.png)

Here the error : 
![image](https://user-images.githubusercontent.com/62793491/212159792-afb9aff6-27ec-48fd-a0ad-bab1c8e8f194.png)

> I have seen on this forum someone having the same issue as me : https://forum.qt.io/topic/120349/run-qt-gui-application-inside-docker/13. I don't really understand how to solve this issue though.

Can you help me please ?

**Comment by fffaraz** [comment]
I can't recommend running your GUI app inside docker but if you really need that you can add "--env="DISPLAY" --net=host" to your docker run args.
