### ISSUE TITLE
Unknown module(s) in QT: webengine

### ISSUE THREAD

**Issue by vinnitu** [fffaraz/docker-qt#14]
Hello!

I am trying to build minimal [example](http://man.hubwiz.com/docset/Qt_5.docset/Contents/Resources/Documents/doc.qt.io/qt-5/qtwebengine-webengine-minimal-example.html)

using docker-compose.yaml like

```
qt:
  image: fffaraz/qt:static
  volumes:
    - ./app:/app
  stdin_open: true
  tty: true
```
got error

```
$ docker-compose exec qt bash
root@5ae058e5429e:/# cd /app
root@5ae058e5429e:/app# qmake
Project ERROR: Unknown module(s) in QT: webengine
```

**Comment by fffaraz** [comment]
Qt webengine is very large and I skip it in my image.
