### ISSUE TITLE
Cross-compile to win64 fails due to serialport dependency

### ISSUE THREAD

**Issue by hanckmann** [fffaraz/docker-qt#8]
When trying to build my application I encounter the following error:

```
root@1b45ef37bffb:/app# qmake
Project ERROR: Unknown module(s) in QT: serialport
```

How can I add the serialport module?
For future reference, how can I add other modules?

**Comment by hanckmann** [comment]
I figured it out!

I added this line: 
    make --jobs=$NPROC JOBS=$NPROC MXE_TARGETS='x86_64-w64-mingw32.static' qtserialport && \

Now the Dockerfile looks like:
```
FROM fffaraz/qt:mxe

RUN \
    cd /opt && \
    git clone https://github.com/mxe/mxe.git && \
    cd /opt/mxe && \
    NPROC=$(($(nproc)+4)) && \
    make --jobs=$NPROC JOBS=$NPROC MXE_TARGETS='x86_64-w64-mingw32.static' qtbase && \
    ln -s /opt/mxe/usr/bin/x86_64-w64-mingw32.static-qmake-qt5 /usr/bin/qmake && \
    qmake --version && \
    make --jobs=$NPROC JOBS=$NPROC MXE_TARGETS='x86_64-w64-mingw32.static' qtserialport && \
    exit 0

ENV PATH="${PATH}:/opt/mxe/usr/bin"
```

This docker image is incredibly useful for cross-compiling Qt applications (since compiling on Windows is a pain). Especially since I now understand how I can add other dependencies!

Thanks!

**Comment by fffaraz** [comment]
I guess you could add `qtserialport ` right after `qtbase`
